---
kind: pipeline
name: build-docker-image
type: kubernetes

steps:
  - name: make-build
    image: golang:1.13-alpine
    pull: if-not-exists
    commands:
      - VERSION=$(head -1 .version)
      - DATE=$(date "+%F,%T")
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 LDFLAGS="-s -w -X main.version=$VERSION -X main.commit=$DRONE_COMMIT_SHA -X main.buildDate=$DATE -X main.builtBy=drone-$DRONE_BUILD_NUMBER " make build
    environment:
      GO111MODULE: on

  - name: build-docker-image-branch
    image: plugins/docker
    settings:
      repo: ${DRONE_REPO,,}
      dockerfile: build/Dockerfile
      tags:
        - ${DRONE_SOURCE_BRANCH/\//-}
        - ${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
      cache_from:
        - ${DRONE_REPO,,}:${DRONE_SOURCE_BRANCH/\//-}
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

---
kind: secret
name: DOCKER_USERNAME
get:
  path: docker-credentials
  name: username
---
kind: secret
name: DOCKER_PASSWORD
get:
  path: docker-credentials
  name: password
---
kind: secret
name: dockerconfigjson
get:
  path: docker-credentials
  name: dockerconfigjson
---
kind: signature
hmac: 2e475c7d3316360f6f6dc1bae393cbee08a0e1454dc4a81b615944ed82b63b86

...
